"""empty message

Revision ID: 5984edc38502
Revises: 97519c3acc64
Create Date: 2016-11-17 03:18:10.277854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5984edc38502'
down_revision = '97519c3acc64'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'addressline1',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('contacts', 'city',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('contacts', 'country',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('contacts', 'zip_or_postcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'zip_or_postcode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('contacts', 'country',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('contacts', 'city',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('contacts', 'addressline1',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###
